### ISSUE TITLE
Can ipywidgets requirement be relaxed?

### ISSUE THREAD

**Issue by rcthomas** [ssciwr/ipywidgets-jsonschema#33]
Thanks for creating this project.  Is the `ipywidgets>=8.0.0b1` requirement strictly necessary?  Is it possible this would work with a bit older ipywidgets and could be relaxed?  Or is it the case that this depends on features only available in 8+?  Thanks again!

**Comment by dokempf** [comment]
Good point. The project that kicked off the development for this one (https://github.com/ssciwr/adaptivefiltering) definitely depends on 8+ as it uses the new `TagsInput` widget. Although that functionality is not part of the core implementation that moved to this repository, I had dropped v7 support in early development because of it. I would need to test and see what incompatibilities there are. Some potential issues come to my mind:

* The tooltip feature has seen a major overhaul in v8 - but v7 might just ignore it
* Setting titles on `Accordion` widgets works differently IIRC

**Comment by rcthomas** [comment]
I tested dropping the requirement to the latest released version (7.7.0) and it seems to run my very simple example notebook.  The widget at least displays, but I don't get any tooltips.

**Comment by dokempf** [comment]
I will double check this with a complex schema from my application and see what happens.

**Comment by rcthomas** [comment]
Hi, I'm just curious if you had a chance to do that double check?  Thanks!
